version: "3.8"

services:
  bizbuddy-web-prod:
    image: bizbuddy-web-prod:1.0.0
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env # Load environment variables from .env
    container_name: bizbuddy-web-prod-1
    ports:
      - "3000:3000"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 5s
      timeout: 5s
      retries: 3
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: "512M"
