---
# Project metadata
name: bizbuddy
version: 0.1.0
private: true
packageManager: pnpm@9.15.2

# NPM scripts for various commands
scripts:
  dev: next dev # Start development server
  build: next build # Build production bundle
  start: next start # Start production server
  lint: next lint # Run linting checks
  deploy: wrangler deploy # Deploy to Cloudflare Workers
  postinstall: prisma generate # Generate Prisma client after install

# Production dependencies
dependencies:
  # Authentication
  "@clerk/nextjs": "^5.7.5"

  # Discord integration
  "@discordjs/rest": "^2.4.2"

  # Form handling
  "@hookform/resolvers": "^3.9.1"
  react-hook-form: "^7.54.2"

  # Database and ORM
  "@neondatabase/serverless": "^0.9.5"
  "@prisma/adapter-neon": "^5.22.0"
  "@prisma/client": "^5.22.0"
  prisma: "^5.22.0"

  # UI Components
  "@radix-ui/react-dialog": "^1.1.4"
  "@radix-ui/react-icons": "^1.3.2"
  "@radix-ui/react-label": "^2.1.1"
  "@radix-ui/react-slot": "^1.1.1"
  "@radix-ui/react-tabs": "^1.1.2"

  # Data management and tables
  "@tanstack/react-query": "^5.62.11"
  "@tanstack/react-table": "^8.20.6"

  # Caching
  "@upstash/redis": "^1.34.3"

  # Styling utilities
  class-variance-authority: "^0.7.1"
  clsx: "^2.1.1"
  tailwind-merge: "^2.6.0"
  tailwindcss-animate: "^1.0.7"

  # Date handling
  date-fns: "^4.1.0"

  # Animation
  framer-motion: "^11.15.0"

  # API and routing
  hono: "^4.6.15"
  next: "^14.2.22"

  # Icons
  lucide-react: "^0.453.0"

  # Theming
  next-themes: "^0.4.4"

  # Core React
  react: "^18.3.1"
  react-dom: "^18.3.1"

  # Code highlighting
  react-syntax-highlighter: "^15.6.1"

  # Payment processing
  stripe: "^17.5.0"

  # Data serialization and validation
  superjson: "^2.2.2"
  zod: "^3.24.1"

  # UI Components
  vaul: "^1.1.2"

  # Deployment
  wrangler: "^3.99.0"

# Development dependencies
devDependencies:
  # Type definitions
  "@cloudflare/workers-types": "^4.20241230.0"
  "@types/node": "^20.17.11"
  "@types/react": "^18.3.18"
  "@types/react-dom": "^18.3.5"
  "@types/react-syntax-highlighter": "^15.5.13"
  discord-api-types: "^0.37.114"

  # Bundle analysis
  "@next/bundle-analyzer": "^15.1.3"

  # Linting and TypeScript
  "@typescript-eslint/eslint-plugin": "^8.19.0"
  "@typescript-eslint/parser": "^8.19.0"
  eslint: "^8.57.1"
  eslint-config-next: 14.2.5
  typescript: "^5.7.2"

  # Styling
  postcss: "^8.4.49"
  tailwindcss: "^3.4.17"
